language: java

sudo: true

group: edge
  
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
os:
  - linux

before_script:
  - echo 'US/Eastern' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script: mvn clean install

branches:
  only:
    - master

after_success:
  - mvn clean test jacoco:report coveralls:report