language: java

sudo: true

group: edge

services:
  - docker

cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
os:
  - linux

before_script:
  - echo 'US/Eastern' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script: mvn clean install

branches:
  only:
    - master

after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker build -t holmes89/liturgy-api:0.$TRAVIS_BUILD_NUMBER .
  - docker build -t holmes89/liturgy-api .
  - docker push holmes89/liturgy-api
  - mvn clean test jacoco:report coveralls:report